const videos = [
  {
    id: "3BFTio5296w",
    title: "Never Gonna Give You Up",
    subtitle: "Music",
    instructions: [
      "Getting started with Vue.js: Installation and setup.",
      "The Vue instance and reactive data.",
      "Template syntax and directives.",
      "Components and props.",
      "State management with Vuex.",
    ],
  },
  {
    id: "3JZ_D3ELwOQ",
    title: "Charlie bit my finger!",
    subtitle: "Entertainment",
    instructions: [
      "Getting started with Vue.js: Installation and setup.",
      "The Vue instance and reactive data.",
      "Template syntax and directives.",
      "Components and props.",
      "State management with Vuex.",
    ],
  },
  {
    id: "9bZkp7q19f0",
    title: "GANGNAM STYLE",
    subtitle: "Music",
    instructions: [
      "Getting started with Vue.js: Installation and setup.",
      "The Vue instance and reactive data.",
      "Template syntax and directives.",
      "Components and props.",
      "State management with Vuex.",
    ],
  },
  {
    id: "CUOY1c_f7F8",
    title: "Mojoman - Above",
    subtitle: "Music",
    instructions: [
      "Getting started with Vue.js: Installation and setup.",
      "The Vue instance and reactive data.",
      "Template syntax and directives.",
      "Components and props.",
      "State management with Vuex.",
    ],
  },
  {
    id: "MeB3eYk1Ze0",
    title: "Ultimate Dog Tease",
    subtitle: "Entertainment",
    instructions: [
      "Getting started with Vue.js: Installation and setup.",
      "The Vue instance and reactive data.",
      "Template syntax and directives.",
      "Components and props.",
      "State management with Vuex.",
    ],
  },
  {
    id: "tPEE9Zk1Ze0",
    title: "Introduction to React",
    subtitle: "Coding",
    instructions: [
      "Getting started with Vue.js: Installation and setup.",
      "The Vue instance and reactive data.",
      "Template syntax and directives.",
      "Components and props.",
      "State management with Vuex.",
    ],
  },
  {
    id: "LQqt0zhTBg8",
    title: "The Art of Web Design",
    subtitle: "Design/Web",
    instructions: [
      "Introduction to the principles of good web design.",
      "Understanding the importance of user experience (UX).",
      "Exploring color schemes and their impact on design.",
      "Responsive design: Ensuring compatibility across devices.",
      "Implementing accessibility features in web design.",
    ],
  },
  {
    id: "eVTXPUF4Oz4",
    title: "In The End - Linkin Park",
    subtitle: "Music",
    instructions: [
      "Discover the story behind the song.",
      "Analyze the lyrical themes and their meaning.",
      "Review the composition and instrumental setup.",
      "Examine the impact of 'In The End' on Linkin Park's career.",
      "Explore fan theories and interpretations of the song.",
    ],
  },
  {
    id: "Y8Ew8Yw9X3k",
    title: "The Future of Technology",
    subtitle: "Tech Trends",
    instructions: [
      "Overview of emerging technology trends.",
      "Deep dive into artificial intelligence (AI) and machine learning.",
      "The rise of quantum computing.",
      "Exploring the future of internet connectivity.",
      "The role of technology in sustainability and green solutions.",
    ],
  },
  {
    id: "XeSKtuwHhOY",
    title: "Nature's Wonders",
    subtitle: "Documentary",
    instructions: [
      "Introduction to Earth's diverse ecosystems.",
      "The beauty and importance of the Amazon rainforest.",
      "Exploring the depths: The mysteries of the ocean.",
      "The Arctic and Antarctic: Life at the poles.",
      "Conservation efforts to protect natural wonders.",
    ],
  },
  {
    id: "xvFZjo5PgG0",
    title: "Understanding TypeScript",
    subtitle: "Coding",
    instructions: [
      "Getting started with TypeScript: Setup and basics.",
      "Understanding types and interfaces.",
      "Advanced types and utility types.",
      "Configuring the TypeScript compiler.",
      "Real-world application: Refactoring JavaScript to TypeScript.",
    ],
  },
  {
    id: "SUXWAEX2jlg",
    title: "React Router Tutorial",
    subtitle: "Coding",
    instructions: [
      "Introduction to routing in single-page applications.",
      "Setting up React Router in your project.",
      "Creating and linking routes.",
      "Dynamic routing and useParams hook.",
      "Nested routes and advanced routing techniques.",
    ],
  },
  {
    id: "Ke90Tje7VS0",
    title: "React Context & Hooks",
    subtitle: "Coding",
    instructions: [
      "Understanding the React Context API.",
      "State management with useContext hook.",
      "The useState hook for component state.",
      "Side effects with the useEffect hook.",
      "Custom hooks for reusable logic.",
    ],
  },
  {
    id: "DPnqb74Smug",
    title: "Next.js & SSR",
    subtitle: "Coding",
    instructions: [
      "What is Server-Side Rendering (SSR)?",
      "Setting up a Next.js project.",
      "Creating pages and using dynamic routes.",
      "Fetching data on the server with getServerSideProps.",
      "Deploying a Next.js application.",
    ],
  },
  {
    id: "I2UBjN5ER4s",
    title: "GraphQL Introduction",
    subtitle: "Coding",
    instructions: [
      "What is GraphQL and how it differs from REST APIs.",
      "Setting up a GraphQL server.",
      "Defining schemas and resolvers.",
      "Executing queries and mutations.",
      "Integrating GraphQL with a frontend application.",
    ],
  },
  {
    id: "MhkGQAoc7bc",
    title: "Vue.js Fundamentals",
    subtitle: "Coding",
    instructions: [
      "Getting started with Vue.js: Installation and setup.",
      "The Vue instance and reactive data.",
      "Template syntax and directives.",
      "Components and props.",
      "State management with Vuex.",
    ],
  },
];
export default videos;
